### ISSUE TITLE
JUnit launches a ValidationError when trying to use ZKTest

### ISSUE THREAD

**Issue by ibonUrrutia** [connollyst/zkunit#1]
**ZKUnit version: 1.1**

When launching a JUnit tests in a class which extends ZKTest, this exception was thrown:

```
org.junit.internal.runners.rules.ValidationError: The @Rule 'rule' must be public.
    at org.junit.internal.runners.rules.RuleMemberValidator$MemberMustBePublic.validate(RuleMemberValidator.java:222)
    at org.junit.internal.runners.rules.RuleMemberValidator.validateMember(RuleMemberValidator.java:99)
    at org.junit.internal.runners.rules.RuleMemberValidator.validate(RuleMemberValidator.java:93)
    at org.junit.runners.BlockJUnit4ClassRunner.validateFields(BlockJUnit4ClassRunner.java:196)
    at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:129)
    at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
    at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
    at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
    at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:33)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4TestClassReference.java:25)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:48)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

I saw that in the current trunk you have already took away that `@Rule` in `ZKTest`. Do you know when are you going to release 1.3?

**Comment by connollyst** [comment]
Hi Ibon,

Yeah, that's a problem I ran into too. `@Rule` didn't play well with the ZK environment I set up and so I rolled back those changes. I personally use v1.0 in my projects, you can use that now to play around. I'll release the trunk (essentially v1.0 again) as v1.3 to avoid any future confusion.

Thanks for bringing this up, let me know if I can help in any way.

Cheers,
Sean

**Comment by ibonUrrutia** [comment]
Hi Sean,
Thank you for your fast reply (and for ZKUnit ;-)). I will change to 1.0 and test it.

Regards,
Ibon

**Comment by connollyst** [comment]
[`org.zkoss.zkunit-1.3`](https://repo1.maven.org/maven2/org/zkoss/zkunit/1.3/) released and up on Maven Central - it's more in line with the documentation too so best to start with that rather than 1.0

Cheers, and thanks again for reporting this.

**Comment by ibonUrrutia** [comment]
I have already tested 1.0 and works perfectly: finally a really nice solution for unit testing ZK! 
Thanks to you!
